// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnAJKs04wcz-5EqtR_G8aJhaq4SnmbGP4',
    appId: '1:792073352600:web:5c8d27d2ddda9e5fff27ed',
    messagingSenderId: '792073352600',
    projectId: 'fruitshop-9828b',
    authDomain: 'fruitshop-9828b.firebaseapp.com',
    storageBucket: 'fruitshop-9828b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtb8MfYxLdi6eJotWXiq6ScMe2iMcPTF8',
    appId: '1:792073352600:android:9b2da4b9a2d32038ff27ed',
    messagingSenderId: '792073352600',
    projectId: 'fruitshop-9828b',
    storageBucket: 'fruitshop-9828b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApwR0wKsvNwJKluHbPQviML4NVZXYc-QI',
    appId: '1:792073352600:ios:97eba4bb4d14ab62ff27ed',
    messagingSenderId: '792073352600',
    projectId: 'fruitshop-9828b',
    storageBucket: 'fruitshop-9828b.appspot.com',
    iosBundleId: 'com.example.fruitShop',
  );
}
